const pages = [
  "pages/welcome/index",
  "pages/auth-entry/index",
  "pages/onboarding/index",
  "pages/body-profile/index",
  "pages/diet-preferences/index",
  "pages/nutrition-plan/index",
  "pages/home/index",
  "pages/food-scanner/index",
  "pages/manual-meal/index",
  "pages/food-catalog/index",
  "pages/food-detail/index",
  "pages/analysis-result/index",
  "pages/portion-adjustment/index",
  "pages/meal-detail/index",
  "pages/meal-records/index",
  "pages/coach/index",
  "pages/profile/index",
  "pages/account-cancellation/index",
  "pages/profile-edit/index",
  "pages/goal-adjust/index",
  "pages/achievements/index",
  "pages/weekly-review/index",
];

export default defineAppConfig({
  pages,
  lazyCodeLoading: "requiredComponents",
  window: {
    navigationStyle: "custom",
    navigationBarBackgroundColor: "#faf9f6",
    navigationBarTextStyle: "black",
    navigationBarTitleText: "Nordic Nutri AI",
    backgroundColor: "#faf9f6",
  },
  tabBar: {
    custom: true,
    color: "#69716b",
    selectedColor: "#153f2b",
    backgroundColor: "#ffffff",
    borderStyle: "white",
    list: [
      { pagePath: "pages/home/index", text: "首页" },
      { pagePath: "pages/meal-records/index", text: "记录" },
      { pagePath: "pages/food-catalog/index", text: "食物库" },
      { pagePath: "pages/coach/index", text: "教练" },
      { pagePath: "pages/profile/index", text: "我的" },
    ],
  },
});
