import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";

const srcRoot = resolve(import.meta.dirname, "../src");

describe("achievement unlock overlay", () => {
  it("mounts the queued celebration overlay in the active page layout", () => {
    const overlay = readFileSync(resolve(srcRoot, "components/achievement-unlock-overlay/index.tsx"), "utf8");
    const modal = readFileSync(resolve(srcRoot, "components/achievement-unlock-modal/index.tsx"), "utf8");
    const app = readFileSync(resolve(srcRoot, "app.tsx"), "utf8");
    const pageLayout = readFileSync(resolve(srcRoot, "layouts/page-layout/index.tsx"), "utf8");
    const pageStyles = readFileSync(resolve(srcRoot, "styles/page.scss"), "utf8");

    expect(pageLayout).toContain("achievementUnlocked");
    expect(modal).toContain("export interface AchievementUnlockModalProps");
    expect(modal).toContain("export function AchievementUnlockModal");
    expect(modal).toContain("particleSeeds");
    expect(modal).toContain("animationDuration");
    expect(overlay).toContain("AchievementUnlockModal");
    expect(modal).toContain("achievement-unlock-overlay");
    expect(modal).toContain("achievement-unlock-overlay__card");
    expect(modal).toContain("achievement-unlock-overlay__particle");
    expect(modal).toContain("particleSizes");
    expect(modal).toContain("achievement-unlock-overlay__sparkle");
    expect(modal).toContain('size={52}');
    expect(modal).toContain('name="x"');
    expect(modal).toContain("achievement-unlock-overlay__burst");
    expect(modal).toContain("achievement-unlock-overlay__burst--left");
    expect(modal).toContain("achievement-unlock-overlay__burst--right");
    expect(modal).toContain('"--particle-mid"');
    expect(modal).toContain('"--particle-scatter"');
    expect(modal).toContain('"--particle-end"');
    expect(modal).not.toContain("成长里程");
    expect(pageLayout).toContain("acknowledgeProductAchievementCelebration");
    expect(modal).not.toContain("useAchievementStore");
    expect(modal).toContain("成就已解锁");
    expect(modal).toContain("收下这份成就");
    expect(modal).toContain("查看全部成就");
    expect(modal).toContain('Taro.navigateTo({ url: "/pages/achievements/index" })');
    expect(pageLayout).toContain("AchievementUnlockModal");
    expect(pageLayout).toContain("<AchievementUnlockModal");
    expect(pageLayout).toContain("useAchievementStore((state) => state.achievementUnlocked)");
    expect(pageLayout).toContain("activeAchievement");
    expect(pageLayout).toContain("useDidHide");
    expect(pageLayout).toContain("pageVisible");
    expect(pageLayout).toContain("{pageVisible ?");
    expect(app).not.toContain("AchievementUnlockOverlay");
    expect(pageStyles).toContain(".achievement-unlock-overlay__burst");
    expect(pageStyles).toContain("achievement-unlock-burst-left");
    expect(pageStyles).toContain("achievement-unlock-burst-right");
    expect(pageStyles).toContain("backdrop-filter: blur(3px)");
    expect(pageStyles).toContain("#d8a94b");
    expect(pageStyles).toContain(".achievement-unlock-overlay__particle--spark");
    expect(pageStyles).toContain("border-radius: 0;");
    expect(pageStyles).toContain("44% {");
    expect(pageStyles).toContain("var(--particle-end) + var(--particle-drift)");
    expect(pageStyles).toContain("var(--particle-fall)");
    expect(pageStyles).toContain(" 500ms both");
    expect(pageStyles).toContain("achievement-unlock-backdrop-in 300ms ease-out");
    expect(pageStyles).toContain("translateY(50px) scale(0.8)");
    expect(pageStyles).toContain("achievement-unlock-icon-glow 2s ease-in-out");
  });
});
