import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { createPortionDraftStore } from "../src/stores/portion-draft-store";
import { mapProductMeal } from "../src/features/meals/product-meal-mapper";
import { toProductMealInput } from "../src/features/meals/product-meal-input";

describe("independent frequent meal templates", () => {
  it("retains template identity across repeat confirmation and clears it for ordinary repeat", () => {
    const meal = mapProductMeal({ id: "source", name: "早餐", mealType: "breakfast", recordedAt: "2026-09-10T00:00:00Z", isFavorite: true, items: [] });
    const store = createPortionDraftStore();
    store.getState().startMealRepeat(meal, "template");
    expect(store.getState().templateId).toBe("template");
    store.getState().startMealRepeat(meal);
    expect(store.getState().templateId).toBeNull();
  });
  it("preserves fractional saved nutrition for repetition", () => {
    const meal = mapProductMeal({ id: "source", name: "早餐", mealType: "breakfast", recordedAt: "2026-09-10T00:00:00Z", isFavorite: false, items: [{ id: "item", name: "鸡蛋", quantityG: 75.5, caloriesPer100g: 123.45, proteinPer100g: 13.65, carbsPer100g: 1.23, fatPer100g: 4.56 }] });
    expect(toProductMealInput(meal).items[0]).toMatchObject({ quantityG: 75.5, proteinPer100g: 13.65, caloriesPer100g: 123.45 });
    const edited = { ...meal, items: meal.items.map((item) => ({ ...item, calories: 186, protein: 20, carbs: 2, fat: 6 })) };
    expect(toProductMealInput(edited).items[0].caloriesPer100g).toBeCloseTo(186 / 0.76);
  });
  it("uses independent templates and has separate save and profile entries", () => {
    const page = readFileSync(new URL("../src/pages/frequent-meals/index.tsx", import.meta.url), "utf8");
    expect(page).toContain("getMealTemplates");
    expect(page).not.toContain("meal.favorite");
    expect(page).toContain("useCount");
    expect(page).toContain("setOpenMenuId");
    expect(page).toContain("frequent-meals__menu");
    expect(page).toContain("frequent-meals__skeleton-card");
    expect(page).toContain("正在加载你的常吃");
    expect(page).toContain("FrequentMealsSkeleton");
    expect(page).toContain("ConfirmDialog");
    expect(page).not.toContain('Taro.showModal({ title: "删除常吃？"');
    expect(page).not.toContain('itemList: ["编辑"');
    expect(page).toContain('>编辑</Text>');
    expect(page).toContain('>删除</Text>');
    expect(page).not.toContain('>重命名</Text>');
    expect(page).not.toContain('>调整默认餐次</Text>');
    expect(page).not.toContain("renameTarget");
    expect(page).not.toContain('name="sparkles"');
    const homeStyles = readFileSync(new URL("../src/components/recent-frequent-meals/index.scss", import.meta.url), "utf8");
    expect(homeStyles).toContain("flex-direction: row");
    expect(homeStyles).toContain("white-space: nowrap");
    const frequentStyles = readFileSync(new URL("../src/pages/frequent-meals/index.scss", import.meta.url), "utf8");
    expect(frequentStyles).toContain("width: auto");
    expect(frequentStyles).toContain("flex: 1 1 auto");
    expect(frequentStyles).toContain("frequent-meals__menu");
    expect(frequentStyles).toContain("frequent-meals-menu-enter");
    expect(frequentStyles).toContain("animation-delay");
    expect(frequentStyles).toContain("&__skeleton-card");
    expect(frequentStyles).toContain("&__loading-status");
    const editorStyles = readFileSync(new URL("../src/pages/frequent-meal-edit/index.scss", import.meta.url), "utf8");
    expect(editorStyles).toContain("grid-template-columns: minmax(0, 1fr)");
    expect(editorStyles).toContain("white-space: nowrap");
    expect(editorStyles).toContain("&__input-shell");
    expect(editorStyles).toContain("&__quantity-input-shell");
    expect(editorStyles).toContain("align-items: center");
    const componentStyles = readFileSync(new URL("../src/styles/components.scss", import.meta.url), "utf8");
    expect(componentStyles).toContain(".confirm-dialog__actions .app-button");
    expect(componentStyles).toContain("height: 80px");
    expect(componentStyles).toContain("z-index: 1200");
    expect(componentStyles).toContain("align-items: center");
    expect(componentStyles).toContain("max-height: calc(100dvh");
    const detailStyles = readFileSync(new URL("../src/styles/page.scss", import.meta.url), "utf8");
    expect(detailStyles).toContain("meal-detail-page__template-action");
    expect(detailStyles).toContain("margin: $space-12 0 $space-48");
    expect(readFileSync(new URL("../src/pages/meal-detail/index.tsx", import.meta.url), "utf8")).toContain("保存到我的常吃");
    expect(readFileSync(new URL("../src/pages/profile/index.tsx", import.meta.url), "utf8")).toContain("我的常吃");
  });
});
